### ISSUE TITLE
First commenter shows 'Someone' username and no Gravatar

### ISSUE THREAD

**Issue by StefMattana** [Automattic/notifications-panel#232] opened 2018-02-16 17:48 UTC
Posting this her under @kwight suggestion :)
 
As the user switched over to WordPress.org recently, their site's Gravatar stopped displaying properly. Even if apparently it looks okay, when heading to their notifications tab we can notices that if someone comments on their posts, the Gravatar doesn't appear. A blank photo appears instead and the user got called as 'Someone' as opposed as their blog name. 

I was able to reproduce the issue myself; here's what we see: 
![aaa](https://user-images.githubusercontent.com/349751/36324591-c952254a-1309-11e8-9e00-afd0169af758.png)
![aaaa](https://user-images.githubusercontent.com/349751/36324594-cb6791e4-1309-11e8-9e16-9fb1c8d8ca4e.png)

I had the user check on different browsers and device as I did, the problem persists. 
Jetpack debug I checked just in case is green.

Any ideas on how to fix it? 

Thanks!

Ticket: 955783-zen

**Comment by kwight** [comment] 2018-02-16 19:02
The missing data in the notif seems to be "post author" data – deeper level comments appear fine since her gravatar is prompted from "commenter" data (for lack of better terms). So, something is off with her site's user (or the data we have for it). This seems supported by the fact that I can't pull up her author archive https://alwayscleia.com/author/alwayscleia (it bounces to the homepage), and I get an error SU'd into Calypso when trying to load her People.

Maybe have her check that her author user on the site is set up fine, with the gravatar showing and the same username she's commenting with? Does she have a funky theme setting like "single user mode" or something (there's also no author info on any of the posts)?

**Comment by kwight** [comment] 2018-02-17 00:02
@gwwar It absultely does, great memory! I'm happy to push that out first thing Monday, look like we stalled on it.

**Comment by StefMattana** [comment] 2018-02-20 10:55
@kwight any news on that perhaps? Sorry for bugging you!

**Comment by rodrigoi** [comment] 2018-02-20 17:13
@StefMattana a fix was deployed yesterday and verified that this user's gravatar shows correctly. I'll close this issue, but let me know if you can't reproduce it or if it happens again.

**Closed by rodrigoi** 2018-02-20 17:13 UTC
Labels: [Pri] Normal, [Type] Bug, [Type] Help Request

**Comment by kwight** [comment] 2018-02-20 17:44
Thanks @rodrigoi !
