### ISSUE TITLE
Arrow down should load more notes

### ISSUE THREAD

**Issue by drw158** [Automattic/notifications-panel#41] opened 2017-05-03 19:14 UTC
Arrow down should load more notes. To test, pull open the new and old clients with a small view port. Arrow down on both. Notice that the old client loads more notes

**Comment by dmsnell** [comment] 2017-05-04 01:32
@drw158 maybe this was just slow when you tried? I cannot reproduce so I'm closing but reopen if you can reproduce

**Closed by dmsnell** 2017-05-04 01:32 UTC
Labels: bug
