### ISSUE TITLE
Device / Browser Testing

### ISSUE THREAD

**Issue by roundhill** [Automattic/notifications-panel#70] opened 2017-05-04 18:39 UTC
Let's test all the things!

## What to test
* Opening / closing of notifications panel animation.
* Infinite scroll.
* Keyboard shortcuts.
* Approve/Unapprove/Spam/Trash a comment. Undo an action.
* Like/Unlike a comment.
* Reply to a comment, with and without a connection.
* Responsiveness to small screen and back again. Should go to full width less than 680px.

## Browser Checklist
**Mac OS**
- [x] Chrome
- [x] Safari
- [x] Firefox

**Windows**
- [x] IE 11
- [x] Edge
- [x] Chrome
- [x] Firefox

**Linux**
- [x] Chrome
- [x] Firefox

**iOS**
- [x] Safari
- [x] Chrome?

**Android**
- [x] Chrome

**Comment by roundhill** [comment] 2017-05-04 19:01
Status message looks off in IE 11:
<img width="402" alt="screen shot 2017-05-04 at 11 59 52 am" src="https://cloud.githubusercontent.com/assets/789137/25720331/653558dc-30c1-11e7-9508-91a57b7cef9e.png">

**Comment by roundhill** [comment] 2017-05-04 19:23
Mobile Safari in landscape isn't full width, not sure if we expect this or not?
![img_3406](https://cloud.githubusercontent.com/assets/789137/25721220/84f6af06-30c4-11e7-9d1a-544a36cd9449.PNG)

**Comment by vindl** [comment] 2017-05-04 19:27
Status message looks off in Firefox:

![firefox glitch on comment reply](https://cloud.githubusercontent.com/assets/1182160/25721345/ee441f2a-30c4-11e7-96d8-0d0fe5a2dde1.png)

**Comment by vindl** [comment] 2017-05-04 19:31
I'm still seeing a sub-pixel rendering issue in Ubuntu and Chrome (works fine in Firefox) which causes a gap to appear between Masterbar and Notifications panel:

![gap](https://cloud.githubusercontent.com/assets/1182160/25721474/73652028-30c5-11e7-8043-41a019dc471f.png)

**Comment by Copons** [comment] 2017-05-04 19:32
> I'm still seeing a sub-pixel rendering issue in Ubuntu and Chrome (works fine in Firefox) which causes a gap to appear between Masterbar and Notifications panel

Might be on Ubuntu only, I still can't see it on Mac.

**Comment by vindl** [comment] 2017-05-04 19:34
When the new notification arrives, the unread notification bell icon flashes but doesn't persist (Chrome, Ubuntu).

**Comment by vindl** [comment] 2017-05-04 19:37
Using <kbd>↑</kbd> and <kbd>↓</kbd> keyboard shortcuts for scrolling works as expected, but when I try using <kbd>J</kbd> and <kbd>K</kbd> it also scrolls the underlying page.

**Comment by Copons** [comment] 2017-05-04 19:39
https://github.com/Automattic/notifications-panel/issues/72 When loading a page on a Jetpack site, after a couple of seconds the panel slides in automatically. (Chrome, Mac)

![may-04-2017 11-45-08](https://cloud.githubusercontent.com/assets/2070010/25719743/50103ece-30bf-11e7-842e-85b407b7dd1a.gif)

**Comment by vindl** [comment] 2017-05-04 19:40
Not sure if this is expected but I can use keyboard shortcuts to switch context after the notifications panel has been closed. To reproduce:
1. Open notifications panel with <kbd>N</kbd>.
2. Verify that it's showing `All` notifications.
3. Close the panel by pressing <kbd>N</kbd>.
4. Press <kbd>C</kbd>.
5. Open the panel again and notice that `Comment` content is now shown.

**Comment by vindl** [comment] 2017-05-04 19:42
Again, not sure what should be the intended behavior but closing the Notifications panel with <kbd>N</kbd> and <kbd>Esc</kbd> works somewhat differently. <kbd>N</kbd> preserves the previous detail view state, while <kbd>Esc</kbd> does not.

**Comment by vindl** [comment] 2017-05-04 20:15
In Chrome on Android the time headings are positioned incorrectly:

<img src="https://cloud.githubusercontent.com/assets/1182160/25723103/86de1c30-30cb-11e7-80a3-559bef1a6184.png" width="300" alt="android" />

I'm also able to scroll the background page when the detail view is opened.

**Comment by dmsnell** [comment] 2017-05-04 21:39
> Using ↑ and ↓ keyboard shortcuts for scrolling works as expected, but when I try using J and K it also scrolls the underlying page.

@vindl @gwwar is working on this in Calypso (disabling those Reader shortcuts while notifications panel is open)

**Comment by roundhill** [comment] 2017-05-04 22:00
> In Chrome on Android the time headings are positioned incorrectly:

Fixed in https://github.com/Automattic/notifications-panel/pull/78

**Comment by apeatling** [comment] 2017-05-04 22:17
All good in Edge.

**Comment by designsimply** [comment] 2017-05-05 22:22
With a comment open, press <kbd>s</kbd> to mark as spam or <kbd>t</kbd> to trash the comment and then press <kbd>u</kbd> to undo. Pressing <kbd>u</kbd> moves focus to the Unread filter instead of undoing as expected.

**Comment by alisterscott** [comment] 2017-05-08 06:12
On Chrome macOS proxied I've noticed this happen a couple of times where a new notification comes in and I can't see any of the other notifications without doing a command-r page refresh. I can't consistently reproduce it though 😐

No console errors

![notifications](https://cloud.githubusercontent.com/assets/128826/25792297/1ac6a756-3409-11e7-8f33-73c9eb33743f.gif)

**Comment by drw158** [comment] 2017-05-15 16:09
Can everyone on this thread retest the issue they reported in the comments? If still an issue, please open a separate GitHub issue. If it's not an issue anymore, maybe react to your comment with a 👎 ?

Thanks for testing!

**Closed** 2017-08-10 09:53 UTC
